#This script will take the output generated by "ExtractSequences.R"
#and reformat it by finding the best alignment for each protein.
#The script returns a .csv file of proteins as columns, species as rows,
#where each cell is the aligned protein for that species.
finalTable=read.csv("SequenceTable.csv")
constructRow=c()
constructCol=c()
tableExists=FALSE
addRow=FALSE
p=1
rowInd=1
while(p < (length(row.names(finalTable)))){
  for(l in 1:length(colnames(finalTable))){
    thisUnit=finalTable[c(p, p+1,p+2), l]
    if(length(which(thisUnit!=" "))>0){
      if(length(which(thisUnit!=" "))>1){
        firstCollapsed=(thisUnit[which(thisUnit!=" ")])[1]
        secondCollapsed=(thisUnit[which(thisUnit!=" ")])[2]
        firstGap=str_count(firstCollapsed, "-")
        secondGap=str_count(secondCollapsed, "-")
        gapMin=min(firstGap,secondGap)
        if(firstGap==gapMin){
          collapsed=(thisUnit[which(thisUnit!=" ")])[1]
        }
        if(secondGap==gapMin){
          collapsed=(thisUnit[which(thisUnit!=" ")])[2]
        }
        constructRow=append(constructRow, collapsed)
      }else{
        collapsed=thisUnit[which(thisUnit!=" ")]
        constructRow=append(constructRow, collapsed)
      }
    }else{
      collapsed=" "
      constructRow=append(constructRow, collapsed)
    }
  }
  if(!tableExists){
    collapsedTable=as.data.frame(constructRow)
    tableExists=TRUE
  }else{
    collapsedTable=as.data.frame(cbind(collapsedTable, constructRow))
  }
  constructRow=c()
  p=p+3
  print(paste("Just made row", rowInd, sep=" "))
  rowInd=rowInd+1
}
collapsedTable=t(collapsedTable)
colnames(collapsedTable)=colnames(finalTable)
write.csv(collapsedTable, file="AllRegionsWithSequences2.csv")
